# Inleiding tot Tensors met PyTorch

Deze notebook behandelt de basis van tensors met behulp van het PyTorch-framework. We zullen bespreken wat tensors zijn, hoe we ze kunnen maken, indexeren, de gegevens erin kunnen manipuleren en de vorm ervan kunnen wijzigen. Elk gedeelte bevat enkele oefeningen om uw begrip te testen.

## Wat zijn Tensors

Tensors zijn een fundamentele gegevensstructuur in veel machine learning-frameworks, waaronder PyTorch. Ze zijn vergelijkbaar met arrays en matrices, maar zijn gegeneraliseerd naar hogere dimensies. Ze kunnen worden gebruikt om verschillende soorten gegevens te vertegenwoordigen, zoals vectors, matrices en zelfs hogere-dimensionale gegevens.

Een tensor kan worden beschouwd als een meerdimensionale array. Tensors kunnen een willekeurig aantal dimensies hebben, en elke dimensie wordt een as genoemd. Hier zijn enkele voorbeelden van tensors van verschillende dimensies:
- Een scalair is een 0-dimensionale tensor.
- Een vector is een 1-dimensionale tensor.
- Een matrix is een 2-dimensionale tensor.
- Een tensor van hogere orde kan drie of meer dimensies hebben.

In [5]:
import torch

# Voorbeeld van een scalair
scalar = torch.tensor(5)
print(scalar)

# Voorbeeld van een vector
vector = torch.tensor([1, 2, 3])
print(vector)

# Voorbeeld van een matrix
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(matrix)

# Voorbeeld van een tensor van hogere orde
tensor = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(tensor)
print(tensor.shape)

tensor(5)
tensor([1, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
torch.Size([2, 2, 2])


## Hoe maak je Tensors

In PyTorch kunnen tensors op verschillende manieren worden gemaakt, bijvoorbeeld door gebruik te maken van torch.tensor(), of door gebruik te maken van functies zoals torch.zeros(), torch.ones(), en torch.arange().

In [2]:
# Een tensor maken van een lijst
a = torch.tensor([1, 2, 3])
print(a)

# Een tensor maken gevuld met nullen
b = torch.zeros(2, 3)
print(b)

# Een tensor maken gevuld met enen
c = torch.ones(4)
print(c)

# Een tensor maken met een range van waarden
d = torch.arange(0, 10, 2)
print(d)


tensor([1, 2, 3])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([1., 1., 1., 1.])
tensor([0, 2, 4, 6, 8])


### Oefening

Maak de volgende tensors:

* Een scalair met de waarde 7.
* Een vector met de waarden [10, 20, 30, 40].
* Een matrix met de waarden [[1, 2], [3, 4], [5, 6]].
* Een 3-dimensionale tensor met de waarden [[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]].
* Een tensor met random waarden met dezelfde shape als de vorige tensor. Tip: rand_like
* Een tensor gevuld met nullen met de vorm (3, 2).
* Een tensor gevuld met enen met de vorm (2, 2, 2).
* Een tensor met de waarden van 0 tot 9.
* Een tensor met willekeurige waarden met de vorm (3, 3).

In [8]:
vraag1 = torch.tensor(7)
vraag2 = torch.tensor([10,20,30,40])
vraag3 = torch.tensor([[1,2], [3,4], [5,6]])
vraag4 = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
vraag5 = torch.rand_like(vraag4, dtype=torch.float)   #dtype niet vergeten want vraag4 tensor heeft geen kommagetallen
print(vraag5)
vraag6 = torch.zeros(3,2)
vraag7 = torch.zeros(2,2,2)
vraag8 = torch.arange(0,9)
vraag9 = torch.rand(3,3)
print(vraag9)

tensor([[[0.6846, 0.0396],
         [0.8874, 0.6539]],

        [[0.3057, 0.1836],
         [0.5652, 0.3845]],

        [[0.9294, 0.6004],
         [0.9677, 0.0466]]])
tensor([[0.1500, 0.5125, 0.0227],
        [0.4960, 0.8714, 0.4024],
        [0.5727, 0.8136, 0.1633]])


# Hoe indexeer je Tensors

Net zoals arrays kunnen tensors worden geïndexeerd om specifieke elementen of delen van de tensor op te halen. Je kunt slicing en integer indexing gebruiken om elementen of sub-tensors te verkrijgen.

In [ ]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Een element ophalen
print(tensor[0, 0])  # Output: 1

# Een rij ophalen
print(tensor[0, :])  # Output: [1, 2, 3]

# Een kolom ophalen
print(tensor[:, 1])  # Output: [2, 5, 8]

# Een sub-tensor ophalen
print(tensor[1:, 1:])  # Output: [[5, 6], [8, 9]]


### Oefening

Gegeven de tensor t = torch.tensor([[10, 20, 30], [40, 50, 60], [70, 80, 90]]), haal de volgende elementen op:

* Het element in de eerste rij en derde kolom.
* De tweede rij.
* De tweede kolom.
* Het sub-tensor bestaande uit de laatste twee rijen en de laatste twee kolommen.

In [9]:
t = torch.tensor([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(t[0, 2])
print(t[1]) # idem aan t[1, :]
print(t[:, 1])
print(t[-2:, -2:])  # idem aan t[1:, 1:]

tensor(30)
tensor([40, 50, 60])
tensor([20, 50, 80])
tensor([[50, 60],
        [80, 90]])


## Hoe manipuleer je de gegevens in Tensors

Je kunt de waarden in een tensor manipuleren door middel van elementgewijze operaties, zoals optellen, aftrekken, vermenigvuldigen en delen.

In [3]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# Optellen
c = a + b
print(c)

# Aftrekken
d = a - b
print(d)

# Vermenigvuldigen
e = a * b
print(e)

# Delen
f = a / b
print(f)

tensor([5, 7, 9])
tensor([-3, -3, -3])
tensor([ 4, 10, 18])
tensor([0.2500, 0.4000, 0.5000])


### Oefening

Gegeven de tensors x = torch.tensor([10, 20, 30]) en y = torch.tensor([1, 2, 3]), voer de volgende bewerkingen uit:

* Tel x en y op.
* Trek y af van x.
* Vermenigvuldig x met y (element gewijs).
* Deel x door y.
* Voeg de x en y tensors samen tot een tensor met shape (2, 3). Tip: cat
* Vermenigvulding x met de getransponeerde van y (matrixvermenigvuldiging). Tip: operator @ en matmul

In [20]:
x = torch.tensor([10, 20, 30])
y = torch.tensor([1, 2, 3])

print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(torch.cat((x.unsqueeze(0),y.unsqueeze(0))))
#print(x.shape)
#print(x.unsqueeze(-1))
print(x @ y.T) # .T want we kunnen niet 1x3 matrix vermenigvuldigen met 1x3 dus moet y omgezet worden naar 3x1 (transponeren)

tensor([11, 22, 33])
tensor([ 9, 18, 27])
tensor([10, 40, 90])
tensor([10., 10., 10.])
tensor([[10, 20, 30],
        [ 1,  2,  3]])
tensor(140)


/tmp/ipykernel_468/2840052004.py:11: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /opt/conda/conda-bld/pytorch_1708025847130/work/aten/src/ATen/native/TensorShape.cpp:3637.)
  print(x @ y.T)


## Hoe manipuleer je de vorm van Tensors

De vorm van een tensor kan worden veranderd met behulp van functies zoals reshape(), view() en transpose().

In [21]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Herschikken van de tensor naar een andere vorm
reshaped_tensor = tensor.reshape(3, 2)
print(reshaped_tensor)

# De tensor transponeren
transposed_tensor = tensor.t()
print(transposed_tensor)


tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


### Oefening

Gegeven de tensor z = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]]), voer de volgende bewerkingen uit:

* Herschik de tensor naar de vorm (4, 2).
* Transponeer de tensor.
* Herschik de tensor naar een 1-dimensionale tensor met 8 elementen.
* Voeg een extra dimensie aan de originele z-vector toe zodat de shape (1,2,4) is. Tip: unsqueeze

In [26]:
z = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])

print(z.reshape(4,2))
print(z.t())
print(z.reshape(8))
#alternatief
print(z.view(-1)) # bekijk de tensor z als een tensor met als shape het argument (-1 voor alles in 1 rij)
print(torch.flatten(z))

print(z.unsqueeze(0))

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[[1, 2, 3, 4],
         [5, 6, 7, 8]]])
